[package]
name = "wsl2-get-display"
version = "1.0.2"
authors = ["Allen Wild <allenwild93@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1"
structopt = { version = "0.3", default-features = false }
