[package]
name = "wsl2-get-display"
version = "0.1.0"
authors = ["Allen Wild <allenwild93@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.32"
clap = { version = "2.33.1", default-features = false }
