[package]
name = "wsl2-get-display"
version = "0.1.1"
authors = ["Allen Wild <allenwild93@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1"
structopt = { version = "0.3", default-features = false }
